//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderServiceModelContainer : DbContext
    {
        public OrderServiceModelContainer()
            : base("name=OrderServiceModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> OrdersSet { get; set; }
        public virtual DbSet<Employees> EmployeesSet { get; set; }
        public virtual DbSet<Products> ProductsSet { get; set; }
        public virtual DbSet<Supplies> SuppliesSet { get; set; }
        public virtual DbSet<Suppliers> SuppliersSet { get; set; }
    }
}
